
target: "results/trans.dd"

paths:
  euroshape : "/home/oskar/Desktop/uio/highRES_GitHub/highRES-Europe-WF/intermediate_data/nuts2/shapes/europe_onshore.geojson"
  existing_lines : "resources/lines.csv"
  existing_links : "resources/links.csv"
  new_lines : "resources/new_lines.csv"
  new_links : "resources/new_links.csv"
  upg_lines : "resources/upgraded_lines.csv"
  upg_links : "resources/upgraded_links.csv"
  tyndp : "resources/tyndp_2020.csv"
  existing_transmission : "resources/existing_transmission.csv"
  transmission_params : "resources/transmission_params.csv"

parameters:
  transmission_alpha : 0.2543