import pathlib
cwd = pathlib.Path().resolve()

## Paths to the inputs

# GEM datasets
excel_solar = config["input_paths"]["excel_solar"]
excel_wind = config["input_paths"]["excel_wind"]
excel_nuclear = config["input_paths"]["excel_nuclear"]

# Shape files
onshore_shapefile_path = config["input_paths"]["onshore_shapefile_path"]
offshore_shapefile_path = config["input_paths"]["offshore_shapefile_path"]

# Techno-economic file
ods_file = config["input_paths"]["ods_file"]

# years for estimation
projected_years = config["parameters"]["projected_years"]

# Get plots of the existing power plants and capacities in Europe
plots = config["parameters"]["plots"]
# Get a csv file for the sheets "gen_lim_z", "gen_exist_z", and "gen_exist_r"
csv_tech_ec = config["parameters"]["csv_tech_ec"]
# paths for the csv files
existing_pcap_r_path = config["parameters"]["existing_pcap_r_path"]
existing_pcap_z_path = config["parameters"]["existing_pcap_z_path"]
gen_lim_z_path = config["parameters"]["gen_lim_z_path"]

## Output filenames
gem_output_path = config["output_names"]["gem_output_path"]
ods_output_file = config["output_names"]["ods_output_file"]

## Extra options
# Get time series for each technology: nuclear, onshore, offshore, solar
time_series = config["parameters"]["time_series"]
time_series_path = config["parameters"]["time_series_path"]

workpath = cwd / pathlib.Path(config["output_names"]["output_folder"])
resources_path = cwd / pathlib.Path("resources")
gem_path = resources_path / pathlib.Path("GEM")

localrules:
    all,
    build_exist_cap,
    build_highres_input,
    plotting_existing_cap,


rule all:
    input:
        expand(workpath / "existing_cap_{year}.finished", year=projected_years)

rule build_exist_cap:
    # Create a csv with columns:
    # "project_name", "Technology","country", "status"
    # "iso_code","lat","lon","capacity_MW",
    # "commissioning_year", "estimated_retirement_year"
    input:
        excel_solar = pathlib.Path(excel_solar),
        excel_wind = pathlib.Path(excel_wind),
        excel_nuclear = pathlib.Path(excel_nuclear),
        onshore_shapefile = pathlib.Path(onshore_shapefile_path),
    output:
        existing_cap = workpath / "installed_capacities.csv",
    notebook:
        "notebooks/build_exist_cap.ipynb"

rule build_highres_input:
    input:
        existing_cap = rules.build_exist_cap.output.existing_cap,
        onshore_shapefile = pathlib.Path(onshore_shapefile_path),
        offshore_shapefile = pathlib.Path(offshore_shapefile_path),
        ods_file = pathlib.Path(ods_file),
    params:
        ods_output_file = workpath / ods_output_file,
    output:
        geodata_file = temp(workpath / "exist_pcap_geom_{year}.geojson"),
        existing_pcap_z_path = (
            workpath / existing_pcap_z_path
            if csv_tech_ec
            else []
        ),
        existing_pcap_r_path = (
            workpath / existing_pcap_r_path
            if csv_tech_ec
            else []
        ),
        gen_lim_z_path = (
            workpath / gen_lim_z_path
            if csv_tech_ec
            else []
        ),
        existing_capacities_full = (
            temp(workpath / "cap_full_temp_{year}.csv")
            if time_series
            else []
        )
    notebook:
        "notebooks/build_highres_exist_cap.ipynb"

rule plotting_existing_cap:
    input:
        geodata_file = rules.build_highres_input.output.geodata_file,
        onshore_shapefile = pathlib.Path(onshore_shapefile_path),
    output:
        plants_in_europe = workpath / "plants_in_europe_{year}.png",
        pcap_in_eur_year = workpath / "capacity_by_nuts2_{year}.png",
        plot_status = temp(touch(workpath / "plots_{year}.finished")),
    notebook:
        "notebooks/exist_pcap_plot.ipynb"

rule build_time_series_country:
    input:
        existing_capacities_full = rules.build_highres_input.output.existing_capacities_full,
    output:
        time_series_path = workpath / time_series_path,
    notebook:
        "notebooks/build_time_series_exist_cap.ipynb"

rule exist_cap_finish:
    input:
        rules.build_highres_input.output.geodata_file,
        (
            rules.plotting_existing_cap.output.plot_status
            if plots
            else []
        ),
        (
            rules.build_time_series_country.output.time_series_path
            if time_series
            else []
        )
    output:
        temp(touch(workpath / "existing_cap_{year}.finished"))








        
